=== mohammed1916/xml-tutorial/University.dtd
<!DOCTYPE university [
	<!ELEMENT university ( (department,course,instructor,teaches)+)>
	<!ELEMENT department ( dept_name, building, budget)>
	<!ELEMENT course ( course_id, title, dept_name, credits)>
	<!ELEMENT instructor (IID, name, dept_name, salary)>
	<!ELEMENT teaches (IID, course_id)>
	<!ELEMENT dept_name ( #PCDATA )>
	<!ELEMENT building ( #PCDATA )>
	<!ELEMENT budget ( #PCDATA )>
	<!ELEMENT course_id ( #PCDATA )>
	<!ELEMENT title ( #PCDATA )>
	<!ELEMENT credits ( #PCDATA )>
	<!ELEMENT IID ( #PCDATA )>
	<!ELEMENT name ( #PCDATA )>
	<!ELEMENT salary ( #PCDATA )>
]>

=== mohammed1916/xml-tutorial/University.xml
<!DOCTYPE university SYSTEM "University.dtd">
<university>
	<department>
		<dept_name name='23'> Comp. Sci. </dept_name>
		<a>s</a>
		<building>Taylor</building>
		<budget>100000</budget>
	</department>
	<department>
		<dept_name> Biology </dept_name>
		<building>Watson</building>
		<budget>90000</budget>
	</department>
	<course>
		<course_id> CS-101</course_id>
		<title>Intro. to Computer Science</title>
		<dept_name> Comp. Sci</dept_name>
		<credits>4</credits>
	</course>
	<course>
		<course_id> BIO-301</course_id>
		<title>Genetics</title>
		<dept_name> Biology</dept_name>
		<credits>4</credits>
	</course>
	<instructor>
		<IID>10101</IID>
		<name>Srinivasan</name>
		<dept_name> Comp. Sci.</dept_name>
		<salary>65000</salary>
	</instructor>
	<instructor>
		<IID>83821</IID>
		<name>Brandt</name>
		<dept_name> Comp. Sci.</dept_name>
		<salary>92000</salary>
	</instructor>
	<instructor>
		<IID>76766</IID>
		<name>Crick</name>
		<dept_name> Biology</dept_name>
		<salary>72000</salary>
	</instructor>
	<teaches>
		<IID>10101</IID>
		<course_id> CS-101</course_id>
	</teaches>
	<teaches>
		<IID>83821</IID>
		<course_id> CS-101</course_id>
	</teaches>
	<teaches>
		<IID>76766</IID>
		<course_id> BIO-301</course_id>
	</teaches>
</university>
